import { Metadata } from "next";
import { ReactNode } from "react";

import NavBar from "@/components/navbar";
import { dasboardStyles as styles } from "@/styles";

export const metadata: Metadata = {
  title: "Fastned by Div-Kodes | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <main className={styles.root_container}>
      <NavBar />
      <section className={styles.children_container}>{children}</section>
    </main>
  );
}
